<?php

// autoload_static.php @generated by Composer

namespace Filter_AI\Vendor\Composer\Autoload;

class ComposerStaticInit6e9b9b7de72c64d03474f0ca4baa05ad
{
    public static $prefixLengthsPsr4 = array (
        'F' =>
        array (
            'Filter_AI\\Vendor\\lucatume\\DI52\\' => 31,
            'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Views_Dir\\' => 47,
            'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Assets_Dir\\' => 48,
            'Filter_AI\\Vendor\\StellarWP\\Telemetry\\' => 37,
            'Filter_AI\\Vendor\\StellarWP\\ContainerContract\\' => 45,
            'Filter_AI\\Vendor\\Psr\\Container\\' => 31,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Filter_AI\\Vendor\\lucatume\\DI52\\' =>
        array (
            0 => __DIR__ . '/..' . '/lucatume/di52/src',
        ),
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Views_Dir\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/telemetry/src/views',
        ),
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Assets_Dir\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/telemetry/src/resources',
        ),
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry',
        ),
        'Filter_AI\\Vendor\\StellarWP\\ContainerContract\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/container-contract/src',
        ),
        'Filter_AI\\Vendor\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
    );

    public static $classMap = array (
        'Filter_AI\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Filter_AI\\Vendor\\Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'Filter_AI\\Vendor\\Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'Filter_AI\\Vendor\\Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
        'Filter_AI\\Vendor\\StellarWP\\ContainerContract\\ContainerInterface' => __DIR__ . '/..' . '/stellarwp/container-contract/src/ContainerInterface.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Admin\\Admin_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Admin/Admin_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Admin\\Resources' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Admin/Resources.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Config' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Config.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Contracts\\Abstract_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Contracts/Abstract_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Contracts\\Data_Provider' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Contracts/Data_Provider.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Contracts\\Runnable' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Contracts/Runnable.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Contracts\\Subscriber_Interface' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Contracts/Subscriber_Interface.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Contracts\\Template_Interface' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Contracts/Template_Interface.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Core' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Core.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Data_Providers\\Debug_Data' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Data_Providers/Debug_Data.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Data_Providers\\Null_Data_Provider' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Data_Providers/Null_Data_Provider.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Events\\Event' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Events/Event.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Events\\Event_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Events/Event_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Exit_Interview\\Exit_Interview_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Exit_Interview/Exit_Interview_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Exit_Interview\\Template' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Exit_Interview/Template.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Last_Send\\Last_Send' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Last_Send/Last_Send.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Last_Send\\Last_Send_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Last_Send/Last_Send_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Opt_In\\Opt_In_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Opt_In/Opt_In_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Opt_In\\Opt_In_Template' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Opt_In/Opt_In_Template.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Opt_In\\Status' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Opt_In/Status.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Telemetry\\Telemetry' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Telemetry/Telemetry.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Telemetry\\Telemetry_Subscriber' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Telemetry/Telemetry_Subscriber.php',
        'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Uninstall' => __DIR__ . '/..' . '/stellarwp/telemetry/src/Telemetry/Uninstall.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\App' => __DIR__ . '/..' . '/lucatume/di52/src/App.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\BuilderInterface' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/BuilderInterface.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\CallableBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/CallableBuilder.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\ClassBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ClassBuilder.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\ClosureBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ClosureBuilder.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\Factory' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/Factory.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\Parameter' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/Parameter.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\ReinitializableBuilderInterface' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ReinitializableBuilderInterface.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\Resolver' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/Resolver.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Builders\\ValueBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ValueBuilder.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\Container' => __DIR__ . '/..' . '/lucatume/di52/src/Container.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\ContainerException' => __DIR__ . '/..' . '/lucatume/di52/src/ContainerException.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\NestedParseError' => __DIR__ . '/..' . '/lucatume/di52/src/NestedParseError.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\NotFoundException' => __DIR__ . '/..' . '/lucatume/di52/src/NotFoundException.php',
        'Filter_AI\\Vendor\\lucatume\\DI52\\ServiceProvider' => __DIR__ . '/..' . '/lucatume/di52/src/ServiceProvider.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6e9b9b7de72c64d03474f0ca4baa05ad::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6e9b9b7de72c64d03474f0ca4baa05ad::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6e9b9b7de72c64d03474f0ca4baa05ad::$classMap;

        }, null, ClassLoader::class);
    }
}
