<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Filter_AI\\Vendor\\lucatume\\DI52\\' => array($vendorDir . '/lucatume/di52/src'),
    'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Views_Dir\\' => array($vendorDir . '/stellarwp/telemetry/src/views'),
    'Filter_AI\\Vendor\\StellarWP\\Telemetry\\Assets_Dir\\' => array($vendorDir . '/stellarwp/telemetry/src/resources'),
    'Filter_AI\\Vendor\\StellarWP\\Telemetry\\' => array($vendorDir . '/stellarwp/telemetry/src/Telemetry'),
    'Filter_AI\\Vendor\\StellarWP\\ContainerContract\\' => array($vendorDir . '/stellarwp/container-contract/src'),
    'Filter_AI\\Vendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
);
