<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit6e9b9b7de72c64d03474f0ca4baa05ad
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Filter_AI\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Filter_AI\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit6e9b9b7de72c64d03474f0ca4baa05ad', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Filter_AI\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit6e9b9b7de72c64d03474f0ca4baa05ad', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Filter_AI\Vendor\Composer\Autoload\ComposerStaticInit6e9b9b7de72c64d03474f0ca4baa05ad::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
